const { prefix, botName } = require('../../config')
const { header, line } = require('../../utils/formatter')

module.exports = {
  name: ['ajuda', 'help', 'menu', 'comandos', 'cmds', 'inicio', 'start'],
  description: 'Mostra todos os comandos disponíveis',
  category: 'Utilidade',
  async execute({ sock, from, msg, isAdmin }) {
    const p = prefix
    const text = [
      header(`🤖 ${botName} — Menu`),
      ``,
      `🎮 *JOGOS*`,
      `┣ ${p}quiz — Trivia (+10💎, +15pts)`,
      `┣ ${p}forca — Forca educativa`,
      `┣ ${p}ppt @u <pedra|papel|tesoura> <ap>`,
      `┣ ${p}velha @u <ap> — Jogo da Velha`,
      `┣ ${p}blackjack <ap> — BJ (hit/stand/double)`,
      `┣ ${p}duelo @u <ap> — Duelo PvP`,
      `┣ ${p}cassino <ap> — Slots`,
      `┣ ${p}raspadinha — Raspadinha (35💎)`,
      `┣ ${p}roleta <ap> <opção> — Roleta`,
      `┣ ${p}crime — Crimes (risco de prisão)`,
      `┗ ${p}minerar — Minerar (🪓 Picareta)`,
      ``,
      `🦹 *ROUBO & VINGANÇA*`,
      `┣ ${p}roubar @u — Sem item (30% sucesso)`,
      `┣ ${p}embebedar @u — Com 🍶 Bond7 (55%)`,
      `┗ ${p}vingar — Vingar-se (💠 VingançaGema)`,
      ``,
      `🏪 *LOJA*`,
      `┣ ${p}loja — Ver itens`,
      `┣ ${p}loja comprar <item>`,
      `┣ ${p}loja comprar seguro — 🔐 Seguro 1h (1500💎)`,
      `┗ ${p}loja inventario`,
      ``,
      `💰 *ECONOMIA*`,
      `┣ ${p}saldo / ${p}carteira`,
      `┣ ${p}diario — Bónus diário + streak 🔥`,
      `┣ ${p}banco saldo|depositar|sacar|juros`,
      `┣ ${p}trabalhar — Ganhar gemas (empregos)`,
      `┣ ${p}trabalhar empregos|mudar <emprego>`,
      `┣ ${p}transferir @u <val> — Enviar gemas`,
      `┣ ${p}lotaria — Lotaria (60💎/bilhete)`,
      `┣ ${p}emprestimo pedir|pagar|ver`,
      `┣ ${p}titulo — Comprar título para o perfil`,
      `┣ ${p}suborno — Reduzir prisão a metade (800💎)`,
      `┣ ${p}historico — Histórico de transacções`,
      `┣ ${p}impostos — Imposto de riqueza`,
      `┗ ${p}fianca — Pagar fiança (sair da prisão)`,
      ``,
      `💘 *SOCIAL*`,
      `┣ ${p}paquerar @u — Tentar a sorte`,
      `┣ ${p}namorar @u / aceitar / recusar / terminar`,
      `┣ ${p}casar @u / aceitar / recusar`,
      `┣ ${p}divorciar — Terminar casamento`,
      `┣ ${p}relacionamento [@u] — Ver estado`,
      `┗ ${p}casaisaleatorios — Formar casais aleatórios`,
      ``,
      `📊 *RANKINGS*`,
      `┣ ${p}rankinggema — Top 10 mais ricos`,
      `┗ ${p}rankingpontos — Top 10 por pontos`,
      ``,
      `🛠️ *UTILIDADE*`,
      `┣ ${p}perfil [@u] — Ver perfil e conquistas`,
      `┣ ${p}sticker — Criar sticker de imagem`,
      `┣ ${p}grupo — Info do grupo`,
      `┗ ${p}ping — Testar bot`,
      isAdmin ? [
        ``,
        `👑 *ADMIN*`,
        `┣ ${p}dar @u <val> / ${p}tirar @u <val>`,
        `┣ ${p}darall <val> — Dar a todos`,
        `┣ ${p}avisar @u <motivo> — Aviso (3=expulsão)`,
        `┣ ${p}avisos @u — Ver/limpar avisos`,
        `┣ ${p}removerwarning @u — Remover advertências`,
        `┣ ${p}infouser @u — Info completa do utilizador`,
        `┣ ${p}promover / ${p}rebaixar @u`,
        `┣ ${p}expulsar @u / ${p}prender @u <min>`,
        `┣ ${p}libertar @u`,
        `┣ ${p}tagall [msg] — Mencionar todos`,
        `┣ ${p}fecharjogo — Encerrar jogo activo`,
        `┣ ${p}silenciar / ${p}abrir — Gerir grupo`,
        `┣ ${p}anuncio <texto> — Anúncio destacado`,
        `┗ ${p}resetar @u — Resetar stats`,
      ].join('\n') : '',
      ``, line(),
    ].filter(l => l !== '').join('\n')

    await sock.sendMessage(from, { text }, { quoted: msg })
  },
}
