const { prefix, botName } = require('../../config')
const { header, line } = require('../../utils/formatter')

module.exports = {
  name: ['ajuda', 'help', 'menu', 'comandos', 'cmds', 'inicio', 'start'],
  description: 'Mostra todos os comandos disponíveis',
  category: 'Utilidade',
  async execute({ sock, from, msg, isAdmin }) {
    const p = prefix
    const text = [
      header(`🤖 ${botName} — Menu`),
      ``,
      `🎮 *JOGOS*`,
      `┣ ${p}quiz — Trivia (30s, +10💎, +15pts)`,
      `┣ ${p}ppt @u <ch> <ap> — PPT vs membro`,
      `┣ ${p}forca — Forca educativa (penalidade/letra)`,
      `┣ ${p}velha @u <ap> — Jogo da Velha vs membro`,
      `┣ ${p}blackjack <ap> — Blackjack (hit/stand/double)`,
      `┣ ${p}duelo @u <ap> — Duelo PvP narrado`,
      `┣ ${p}cassino <ap> — Slots`,
      `┣ ${p}crime — Comete crimes (risco de prisão)`,
      `┗ ${p}minerar — Minerar (🪓 Picareta obrigatória)`,
      ``,
      `🦹 *ROUBO & VINGANÇA*`,
      `┣ ${p}roubar @u — Sem item (30% sucesso)`,
      `┣ ${p}embebedar @u — Com 🍶 Bond7 (55% sucesso)`,
      `┗ ${p}vingar — Requer 💠 VingançaGema (2h)`,
      ``,
      `🏪 *LOJA & INVENTÁRIO*`,
      `┣ ${p}loja — Ver itens à venda`,
      `┣ ${p}loja comprar <item>`,
      `┗ ${p}loja inventario`,
      ``,
      `💰 *ECONOMIA*`,
      `┣ ${p}saldo / ${p}carteira`,
      `┣ ${p}diario — Bónus + streak 🔥`,
      `┣ ${p}banco saldo|dep|sacar|juros`,
      `┣ ${p}trabalhar — Trabalhar por gemas`,
      `┣ ${p}trabalhar empregos|mudar <nome>`,
      `┣ ${p}transferir @u <val>`,
      `┗ ${p}fianca — Sair da prisão`,
      ``,
      `💘 *SOCIAL & AMOR*`,
      `┣ ${p}paquerar @u — Tenta a tua sorte! 😏`,
      `┣ ${p}namorar @u — Pede em namoro`,
      `┣ ${p}namorar aceitar/recusar/terminar`,
      `┣ ${p}casar @u — Proposta (${require('../../config').shop ? '100💎' : ''})`,
      `┣ ${p}casar aceitar/recusar`,
      `┣ ${p}divorciar — Divórcio (80💎)`,
      `┗ ${p}relacionamento [@u] — Ver status`,
      ``,
      `📊 *RANKINGS*`,
      `┣ ${p}rankinggema — Top 10 mais ricos`,
      `┗ ${p}rankingpontos — Top 10 por pontos`,
      ``,
      `🛠️ *UTILIDADE*`,
      `┣ ${p}sticker — Criar sticker de imagem`,
      `┣ ${p}perfil [@u] — Perfil + conquistas`,
      `┣ ${p}grupo — Info do grupo`,
      `┗ ${p}ping`,
      isAdmin ? [
        ``,
        `👑 *ADMIN*`,
        `┣ ${p}dar / ${p}tirar @u <val>`,
        `┣ ${p}darall <val> — dar a todos`,
        `┣ ${p}avisar @u <motivo> — aviso (3=expulsão)`,
        `┣ ${p}avisos @u — ver/limpar avisos`,
        `┣ ${p}infouser @u — info completa do user`,
        `┣ ${p}promover / ${p}rebaixar @u`,
        `┣ ${p}expulsar / ${p}prender @u <min>`,
        `┣ ${p}libertar @u`,
        `┣ ${p}tagall [msg] — mencionar todos`,
        `┣ ${p}fecharjogo — fechar jogo activo`,
        `┣ ${p}silenciar / ${p}abrir`,
        `┣ ${p}anuncio <texto>`,
        `┗ ${p}resetar @u`,
      ].join('\n') : '',
      ``, line(),
    ].filter(l => l !== '').join('\n')

    await sock.sendMessage(from, { text }, { quoted: msg })
  },
}
