const { prefix, botName } = require('../../config')
const { header, line } = require('../../utils/formatter')

module.exports = {
  name: ['ajuda', 'help', 'menu', 'comandos', 'cmds', 'inicio', 'start'],
  description: 'Mostra todos os comandos disponíveis',
  category: 'Utilidade',
  async execute({ sock, from, msg, isAdmin }) {
    const p = prefix
    const text = [
      header(`🤖 ${botName} — Menu`),
      ``,
      `🎮 *JOGOS*`,
      `┣ ${p}quiz `,
      `┣ ${p}forca`,
      `┣ ${p}ppt @u <pedra|papel|tesoura> <ap>`,
      `┣ ${p}velha @u <ap>`,
      `┣ ${p}blackjack <ap>`,
      `┣ ${p}duelo @u <ap>`,
      `┣ ${p}cassino <ap>`,
      `┣ ${p}raspadinha — (35💎)`,
      `┣ ${p}roleta <ap> <opção>`,
      `┣ ${p}crime — (risco de prisão)`,
      `┗ ${p}minerar — (🪓 Picareta)`,
      ``,
      `🦹 *ROUBO & VINGANÇA*`,
      `┣ ${p}roubar @u — (30% sucesso)`,
      `┣ ${p}embebedar @u — Com 🍶 Bond7 (55%)`,
      `┗ ${p}vingar — (💠 VingançaGema)`,
      ``,
      `🏪 *LOJA*`,
      `┣ ${p}loja — Ver itens`,
      `┣ ${p}loja comprar <item>`,
      `┣ ${p}loja comprar seguro — 🔐 Seguro 1h (500💎)`,
      `┗ ${p}loja inventario`,
      ``,
      `💰 *ECONOMIA*`,
      `┣ ${p}saldo / ${p}carteira`,
      `┣ ${p}diario — streak 🔥`,
      `┣ ${p}banco saldo|depositar|sacar|juros`,
      `┣ ${p}trabalhar — (empregos)`,
      `┣ ${p}trabalhar empregos|mudar <emprego>`,
      `┣ ${p}transferir @u <val>`,
      `┣ ${p}loteria — (60💎/bilhete)`,
      `┣ ${p}emprestimo pedir|pagar|ver`,
      `┣ ${p}titulo — Comprar título para o perfil`,
      `┣ ${p}suborno — Reduzir prisão a metade (200💎)`,
      `┣ ${p}historico — Histórico de transacções`,
      `┣ ${p}impostos`,
      `┗ ${p}fianca — (sair da prisão)`,
      ``,
      `💘 *SOCIAL*`,
      `┣ ${p}paquerar @u `,
      `┣ ${p}namorar @u / aceitar / recusar / terminar`,
      `┣ ${p}casar @u / aceitar / recusar`,
      `┣ ${p}divorciar `,
      `┣ ${p}relacionamento [@u]`,
      `┗ ${p}casaisaleatorios `,
      ``,
      `📊 *RANKINGS*`,
      `┣ ${p}rankinggema`,
      `┗ ${p}rankingpontos `,
      ``,
      `🛠️ *UTILIDADE*`,
      `┣ ${p}perfil [@u] `,
      `┣ ${p}sticker — Criar sticker de imagem`,
      `┣ ${p}grupoo`,
      `┗ ${p}ping — Testar bot`,
      isAdmin ? [
        ``,
        `👑 *ADMIN*`,
        `┣ ${p}dar @u <val> / ${p}tirar @u <val>`,
        `┣ ${p}darall <val> — Dar a todos`,
        `┣ ${p}avisar @u <motivo> — Aviso (3=expulsão)`,
        `┣ ${p}avisos @u — Ver/limpar avisos`,
        `┣ ${p}removerwarning @u — Remover advertências`,
        `┣ ${p}infouser @u — Info completa do utilizador`,
        `┣ ${p}promover / ${p}rebaixar @u`,
        `┣ ${p}expulsar @u / ${p}prender @u <min>`,
        `┣ ${p}libertar @u`,
        `┣ ${p}tagall [msg] — Mencionar todos`,
        `┣ ${p}fecharjogo — Encerrar jogo activo`,
        `┣ ${p}silenciar / ${p}abrir — Gerir grupo`,
        `┣ ${p}anuncio <texto> — Anúncio destacado`,
        `┗ ${p}resetar @u — Resetar stats`,
      ].join('\n') : '',
      ``, line(),
    ].filter(l => l !== '').join('\n')

    await sock.sendMessage(from, { text }, { quoted: msg })
  },
}
